language: php
php:
- '5.5'

script: echo "We don't have tests yet :("

before_deploy:
- sh config.sh
- sh package.sh

deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key:
    secure: HU3WGtEu3FeOTqfQI0E4/7UswhnsGJpq5/5IMwAPTmAvJaGDlNbu9ZKe4bOhsd8Pesskq9UF750qTSJjuHx8E02/ZLHP9/XVG/fpaI7FALy/CUq9+stEn5UWgxTsjOpEtvHR2Qkg6zzvwjNpW9imQEx0Ywh3VmxWiR0CU/dEyml1fAGPumpw5HnGptlZJVfXERADn4eDfBpGb6GTgc17nQyNSCxKjajW90QxuRNQZb4ZG2F46YIYZPTgRMOibvLJJSRHACc5tfxyABRDjZl5KnTatjtJmtQzR9Tr9SPM4tLGlJ35/EKR3xHC/ub2ITvNMOuRJKsoW3Gd78n+PG5mz88b0Z4kuoYeelGKv3axwUpSrmj/oP6JExhhKWLpQWMaXRVyjpg5HX0EJZ9hPRFGzBQrWzjiX9bf1kRVBTQzSBwnkmbwN34Ktp04oCJQWLbsXj0Z2DaDq4XESMdDa5oAqfT6aKdBP06jdQPVnIZKVDYgFn6wfW5svfnmQ9NEulGY3SjhXeqy9fxgF2VL3MD3wxjAxP8aW0D2QRC/mKhpm+IyxrY9HQtG8PTRXS0JcSMPnCs2bdQVyQ5JybJZtrf0m/v6U+6VOnYHOf3NLZGKMNy6+X/GwWhCOJY41CKqrX7TvimLxwBRLOtiHJBk29yCyGe2xuroApMafE0b1jpIFCU=
  file: "plugin-transbank-onepay-opencart3-$TRAVIS_TAG.ocmod.zip"
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-opencart-onepay
    tags: true
