#!/usr/bin/env bash
docker-compose up -d && \
echo "
========================================

      🌎 Web server: http://localhost/

      ⚙️ Admin: http://localhost/admin
            
            user: user
            password: bitnami1

========================================"
